trigger: none
pool: newagent
steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      backendServiceArm: 'SCS'
      backendAzureRmStorageAccountName: 'raju007stgankit'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'uma.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      environmentServiceNameAzureRM: 'SCS'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      environmentServiceNameAzureRM: 'SCS'